### ISSUE TITLE
Error: Cannot find module '<LOCAL MODULE>'

### ISSUE THREAD

**Issue by StarpTech** [keymetrics/pmx#34]
After update from 0.3.9 to 0.3.16 I get an error that my app dependency cannot be found. I solve this problem by require all my modules at the top instead after `require('pmx').init();`

```
Error: Cannot find module 'good'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.<anonymous> (E:\Vagrant\Ubuntu1404\webapp\node_modules\pmx\lib\transaction.js:62:21)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at E:\Vagrant\Ubuntu1404\webapp\index.js:93:15
    at E:\Vagrant\Ubuntu1404\webapp\node_modules\glue\lib\index.js:148:9
    at done (E:\Vagrant\Ubuntu1404\webapp\node_modules\glue\node_modules\items\lib\index.js:30:25)
    at done (E:\Vagrant\Ubuntu1404\webapp\node_modules\glue\node_modules\items\lib\index.js:30:25)
    at done (E:\Vagrant\Ubuntu1404\webapp\node_modules\hapi\node_modules\items\lib\index.js:30:25)
    at E:\Vagrant\Ubuntu1404\webapp\api\lib\index.js:165:9
    at E:\Vagrant\Ubuntu1404\webapp\api\lib\db.js:81:5
    at E:\Vagrant\Ubuntu1404\webapp\api\node_modules\mongodb\lib\mongo_client.js:403:11
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by niabb** [comment]
Same error here.

**Comment by bazineta** [comment]
Same issue...subscribing.

**Comment by JChefKennedy** [comment]
same problem...makes the whole software unusable

**Comment by Unitech** [comment]
With the same module `good` ?

**Comment by Unitech** [comment]
There is not any [*good* module required](https://github.com/keymetrics/pmx/search?utf8=%E2%9C%93&q=good) that's strange

**Comment by bazineta** [comment]
Further detail....the module that it'll error on isn't a pmx dependency, rather, it's one of our own, loaded after pmx.  Here's where we see it, in our mainline:

```
pmx.init()

# Many lines of Mongoose model registration and Express startup omitted

process.on 'message', (message) ->
  if message is 'shutdown'
    require('broker').exit()
    process.exit 0
  return
```

That broker require is a socket-based broker talking to other backend systems, and we're asking it to shut down persistent connections.  We can't require it earlier, as it depends on Mongoose models that won't yet be registered if we do it earlier, so here in the mainline, this is where we need to require it.

However, when we do so here, we'll get the same 'Cannot find module' error on the broker module as described by others here.  It resides in a node_modules directory immediately below our mainline app.coffee, and this worked fine until the pmx upgrade as described in the OP.

**Comment by btmdave** [comment]
Same issue here, anyone find a solution?

**Comment by lcalvy** [comment]
hi, same issue with baucis module,

```
Error: Cannot find module 'baucis' at Function.Module._resolveFilename (module.js:336:15) at Function.Module._load (module.js:278:25) at Function.<anonymous> (/app/node_modules/pmx/lib/transaction.js:47:40) at Module.require (module.js:365:17) at require (module.js:384:17) at EventEmitter.<anonymous> (/app/core/web.js:51:18) at EventEmitter.emit (events.js:107:17) at register (/app/node_modules/kraken-js/node_modules/meddleware/index.js:218:24) at Array.forEach (native) at EventEmitter.onmount (/app/node_modules/kraken-js/node_modules/meddleware/index.js:203:14) at EventEmitter.g (events.js:199:16) at EventEmitter.emit (events.js:129:20) at EventEmitter.<anonymous> (/app/node_modules/express/lib/application.js:237:8) at Array.forEach (native) at EventEmitter.use (/app/node_modules/express/lib/application.js:216:7) at middleware (/app/node_modules/kraken-js/lib/middleware.js:29:9) at tryCatch1 (/app/node_modules/kraken-js/node_modules/bluebird/js/main/util.js:63:19) at Promise$_callHandler [as _callHandler] (/app/node_modules/kraken-js/node_modules/bluebird/js/main/promise.js:695:13) at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/app/node_modules/kraken-js/node_modules/bluebird/js/main/promise.js:711:18) at Promise$_settlePromiseAt [as _settlePromiseAt] (/app/node_modules/kraken-js/node_modules/bluebird/js/main/promise.js:868:14) at Promise$_settlePromises [as _settlePromises] (/app/node_modules/kraken-js/node_modules/bluebird/js/main/promise.js:1006:14) at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/app/node_modules/kraken-js/node_modules/bluebird/js/main/async.js:74:12) at Async$consumeFunctionBuffer (/app/node_modules/kraken-js/node_modules/bluebird/js/main/async.js:37:14) at process._tickDomainCallback (node.js:381:11) Exception
» 2 Oct 2015 14:05:00.752 2015-10-02 12:05:26.616546+00:00 app web.2 - -
```

This occur when I add this code in top of application.js

```javascript
// track https request in keymetrics
pmx = require('pmx').init({
    http: true
});
```

**Comment by lklepner** [comment]
I'm experiencing the same issue - 
https://github.com/keymetrics/pmx/issues/57

**Comment by cheri3a** [comment]
same problme her
