### PR TITLE
Stop clearing main module's paths

### LINKED ISSUE #34: Error: Cannot find module '<LOCAL MODULE>'
After update from 0.3.9 to 0.3.16 I get an error that my app dependency cannot be found. I solve this problem by require all my modules at the top instead after `require('pmx').init();`

```
Error: Cannot find module 'good'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.<anonymous> (E:\Vagrant\Ubuntu1404\webapp\node_modules\pmx\lib\transaction.js:62:21)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at E:\Vagrant\Ubuntu1404\webapp\index.js:93:15
    at E:\Vagrant\Ubuntu1404\webapp\node_modules\glue\lib\index.js:148:9
    at done (E:\Vagrant\Ubuntu1404\webapp\node_modules\glue\node_modules\items\lib\index.js:30:25)
    at done (E:\Vagrant\Ubuntu1404\webapp\node_modules\glue\node_modules\items\lib\index.js:30:25)
    at done (E:\Vagrant\Ubuntu1404\webapp\node_modules\hapi\node_modules\items\lib\index.js:30:25)
    at E:\Vagrant\Ubuntu1404\webapp\api\lib\index.js:165:9
    at E:\Vagrant\Ubuntu1404\webapp\api\lib\db.js:81:5
    at E:\Vagrant\Ubuntu1404\webapp\api\node_modules\mongodb\lib\mongo_client.js:403:11
    at process._tickDomainCallback (node.js:381:11)
```

### PR DESCRIPTION
**Pull request by nickclaw**
Closes #34 and #56.

Without this fix, the following code fails with: `Error: Cannot find module 'express'`

```js
var pmx = require('pmx');
pmx.init();

setTimeout(function() {
    require('express');
}, 1000);
```

Happy to add a test case if you need it, wasn't sure where to put it.

### CODE REVIEW

**Comment by Unitech** [comment]
interesting, could you put a test file for this here: https://github.com/keymetrics/pmx/tree/master/test

**Comment by nickclaw** [comment]
@Unitech done!

**Comment by Unitech** [comment]
awesome thanks
